export default {
  shoes: {
    Apex_ashpalt2: require(`./assets/shoes/Apex_ashpalt2.jpg`),
    Apex_brdx2: require(`./assets/shoes/Apex_brdx2.jpg`),
    Apex_eclipse2: require(`./assets/shoes/Apex_eclipse2.jpg`),
    Apex_hazelnut2: require(`./assets/shoes/Apex_hazelnut2.jpg`),
    Apex_jetgum2: require(`./assets/shoes/Apex_jetgum2.jpg`),
    Apex_liqgld2: require(`./assets/shoes/Apex_liqgld2.jpg`),
    Apex_mars3: require(`./assets/shoes/Apex_mars3.jpg`),
    Apex_mirror3: require(`./assets/shoes/Apex_mirror3.jpg`),
    Apex_slkgum2: require(`./assets/shoes/Apex_slkgum2.jpg`),
    Cylinder_brdeaux2: require(`./assets/shoes/Cylinder_brdeaux2.jpg`),
    Cylinder_gldbar2: require(`./assets/shoes/Cylinder_gldbar2.jpg`),
    Cylinder_jetpyth2: require(`./assets/shoes/Cylinder_jetpyth2.jpg`),
    Cylinder_liqsil2: require(`./assets/shoes/Cylinder_liqsil2.jpg`),
    Cylinder_nautical2: require(`./assets/shoes/Cylinder_nautical2.jpg`),
    Cylinder_oilarm2: require(`./assets/shoes/Cylinder_oilarm2.jpg`),
    Cylinder_scrpyth2: require(`./assets/shoes/Cylinder_scrpyth2.jpg`),
    Prism_armgum1: require(`./assets/shoes/Prism_armgum1.jpg`),
    Prism_blkalrt1: require(`./assets/shoes/Prism_blkalrt1.jpg`),
    Prism_dolphin1: require(`./assets/shoes/Prism_dolphin1.jpg`),
    Prism_gldbar1: require(`./assets/shoes/Prism_gldbar1.jpg`),
    Prism_honey: require(`./assets/shoes/Prism_honey.jpg`),
    straightJacket_oil2: require(`./assets/shoes/straightJacket_oil2.jpg`),
  },
  stretch: require(`./assets/shoes/stretch.jpg`),
};
